# This file was generated by GoReleaser. DO NOT EDIT.
cask "notty" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "debb63893405ab3e845b2d9ed782c590e0f218e7a3500ae8f1bf4f09f8a0087c"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e408b7168a9a2c5321464ed5416ef44af9a72e2bcd626ef732ac1b997ab369f5"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "12c98c704f4d68b774117ebf9aa009afd0ade57cce9d9b15b525bf430e7a87f0"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe6265695368ef11c0a17ca01d128444ec55067ab0ad33cd2b37cf4fe538e255"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_linux_amd64.tar.gz"
    end
  end

  name "notty"
  desc "Terminal markdown notes app"
  homepage "https://github.com/mathieucroset/notty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notty"]
    end
  end

  # No zap stanza required
end
