# This file was generated by GoReleaser. DO NOT EDIT.
cask "notty" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "626609402ec177b2f063ea979437a74f4c44a0ca7f840364d790e2ad2084528c"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a5adb9ecd316996e4201794e0f53629b5ca4e298216eb751df1a03d1d02102ce"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8ea3eab3e9d51af2e6b21028a642fb5340474294bc44f73b19f14def59bbe9c4"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4412a5778771d16c2b6e01a10113ff5a9d92881495976d187e25d5c6fec6bb05"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_linux_amd64.tar.gz"
    end
  end

  name "notty"
  desc "Terminal markdown notes app"
  homepage "https://github.com/mathieucroset/notty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notty"]
    end
  end

  # No zap stanza required
end
