# This file was generated by GoReleaser. DO NOT EDIT.
cask "notty" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "5df47e75b8b7bd07ca1b78830ebeecb9f3365c5fe801844eb5b177062532836d"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "787d7d15783d309eb860e399c096cd6c38969e16ef6b3fe7348c482cc7fabc7f"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8734a37346d95ec027cde5712ca91dc8fe8559e560c3c77360086a28e80d205a"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9645f3b74abf5752e53d73fd7a035c0d25bbccc2ba11c82e30c0e4480bdaeec"
      url "https://github.com/mathieucroset/Notty/releases/download/v#{version}/notty_#{version}_linux_amd64.tar.gz"
    end
  end

  name "notty"
  desc "Terminal markdown notes app"
  homepage "https://github.com/mathieucroset/notty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "notty"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/notty"]
    end
  end

  # No zap stanza required
end
